* Introduction
  For many years I have been using various editors/IDEs on Windows such as M$ Visual Studio.
  I can't say that they are terrible, in fact, many people like such kind of software 
  but, on the other hand, it would be very interesting to try out something complitely different.
  So in May 2010 I started to use GNU Emacs for development and writing.

  In this file I will describe various problems I encountered and its solutions.
  It looks like that Emacs Org mode is quite convenient to keep notes of such kind.


* To Study

** Master Emacs Org mode
   Probably I would like to use it to organize my to-do lists.
   I love the idea that its just simple text.


* In Progress

** spell check
   I need spell check my writings including this file and also comments in my code.
   Is integration with After the Deadline possible?

   Trying flyspell-mode which works with Cygwin aspell program.

** TFS integration
   Microsoft Team Foundation server (TFS) has terrible version control system desendant of VSS.
   Required a way to do simple operation like file check out from Emacs
   
** Unix shell inside Emacs on Windows
   Something like git's shell (MinGW or Cygwin bash).

   Trying to use Cygwin bash...

** Configuration refactoring
   My .emacs file is growing and it would be better to split it into several separate files.
   For example: emacs.el, basic.el, programming.el, projects.el etc
   It also should contain configuration for several hosts.

** Git repository for Emacs configuration
   Use Git repository on github to keep my config's history and sync it between hosts.

** Additional software list
   Create list of additional software like git, cygwing etc that should be installed 
   to create Unix like environment on Win host for Emacs.
   
** iBuffer
   Set up iBuffer instead of old buffer list

** Tags (etags or ctags)
   Need support for JavaScript, Html, Css, C#
   

* Notes

** Highlight current line in Dired
   I need line highligthing only in Dired and it should follow my dark twilight Emacs theme.
   So hl-line-face should be customized and the hook added on Dired start up:
   
   (setq hl-line-face '((t (:background "#27292A"))))
   (add-hook 'dired-mode-hook (lambda () (hl-line-mode 1)))

** mk-project
   I've found very interesting tool for Emacs called [[http://github.com/mattkeller/mk-project][mk-project]].

   It's required Unix commands such as find and I copied the part of Matt Keller's config
   for Windows to solve the problem. It adds cygwin/bin to PATH and make Cygwin a default shell for Emacs.
   Now it's just temporary solution but I'am going to consider Cygwin env as my main shell on Windows.

   Configured using index-find-cmd and grep-find-cmd because I needed to exclude not only version controls
   directory but also bin, obj, log etc.
   
   I'am going to try out ack for search (requires Perl, hope it will work under Cygwin).

** .Net code editing
   Inspite of working mainly with JavaScript I sometimes edit C# and aspx,
   so it would be great to get at least code coloring for them.

   Added csharp-mode.el, it provides syntax coloring for C# code.
   Tried aspx-mode.el but it looks like that it doesn't work proprely in my case for unknown reason.
   The mode also contains several extra dependencies (espresso.el, multy-mode.el).
   
** Control and Meta under thumbs mapping
   Emacs default binding were designed for keyboards that have another key's positions than modern ones.
   For example, The Space-cadet keyboard has Contorls keys at the both sides of Space key, so it's convinient
   to press controls with thumbs. A modern keyboard has Controls under pinkies that leads to RSI due to heavy usage
   of shortcuts with Ctrl key. For instance, I can't press many cursor moving commands without shifting my hands
   from default typing possition. And it's slow, not so much as pressing arrows but still slow.

   Currently I'm trying the following on my Samsung N148 netbook:
   Win - Fn - Alt - Control - Space - Control - Alt - ContextMenu.
   I've used KeyTweak (on Windows XP) to remap the keys.
   
   Netbook's keyboard is small so it's convinient to press both Control and Alt with thumbs.
   On a bigger keyboard Alt key will be under unnamed finger that looks nice because it's used not so often.
   With such mapping pinkies are used only for pressing Shifts that are big and easily reachable.
   

   
   
