* Introduction
  I started to use Emacs about a month ago instead of MS Visual Studio 2010 and couple of other text editors.
  In this file I would like to describe various problems I encountered and its solutions.
  It looks like that Emacs Org mode is quite convinient to keep notes of such kind.
  So let start.


* To Study

** Master Emacs Org mode
   Probably I would like to use it to organize my to-do lists.
   I love the idea that its just simple text.


* ToDo's

** spell check
   I need spell check my writings including this file and also comments in my code.
   Is integration with After the Deadline possible?

** .Net code editing
   Inspite of working mainly with JavaScript I sometimes edit C# and aspx,
   so it would be great to get at least code coloring for them.

** TFS integration
   Microsoft Team Foundation server (TFS) has terrible version control system desendant of VSS.
   Required a way to do simple operation like file check out from Emacs
   
** Unix shell inside Emacs on Windows
   Something like git's shell (MinGW or Cygwin bash).

** Configuration refactoring
   My .emacs file is growing and it would be better to split it into several separate files.
   For example: emacs.el, basic.el, programming.el, projects.el etc
   It also should contain configuration for several hosts.

** Git repository for Emacs configuration
   Use Git repository on github to keep my config's history and sync it between hosts.

** Additional software list
   Create list of additional software like git, cygwing etc that should be installed 
   to create Unix like environment on Win host for Emacs.


* Notes & Solved Problems

** Highlight current line in Dired
   I need line highligthing only in Dired and it should follow my dark twilight Emacs theme.
   So hl-line-face should be customized and the hook added on Dired start up:
   
   (setq hl-line-face '((t (:background "#27292A"))))
   (add-hook 'dired-mode-hook (lambda () (hl-line-mode 1)))

** mk-project
   I've found very interesting tool for Emacs called [[http://github.com/mattkeller/mk-project][mk-project]].
   It's required Unix commands such as find and I copied the part of Matt Keller's config
   for Windows to solve the problem. It adds cygwin/bin to PATH and make Cygwin a default shell for Emacs.
   Now it's just temporary solution but I'am going to consider Cygwin env as my main shell on Windows.


   
